---
- name: Atualizar pacotes do sistema
  hosts: local
  gather_facts: true
  become: true
  tasks:
    - name: Atualizar cache do apt
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Executar upgrade dos pacotes
      ansible.builtin.apt:
        upgrade: dist
